MATCH (n) DETACH DELETE n;

DROP CONSTRAINT ON (P:User) ASSERT P.mid IS UNIQUE;
DROP CONSTRAINT ON (T:Tweet) ASSERT T.mid IS UNIQUE;

CREATE CONSTRAINT ON (P:User) ASSERT P.mid IS UNIQUE;
CREATE CONSTRAINT ON (T:Tweet) ASSERT T.mid IS UNIQUE;